// Generated by CoffeeScript 1.3.3
(function() {
  var qry1, qry2;

  qry1 = Harvey.attach('screen and (min-width:768px)', {
    setup: function() {
$(function() {
  $('ul.side-nav a').bind('click',function(event){
    var $anchor = $(this);
    /*
    if you want to use one of the easing effects:
    $('html, body').stop().animate({
      scrollLeft: $($anchor.attr('href')).offset().left
    }, 1500,'easeInOutExpo');
     */
    $('html, body').stop().animate({
      scrollLeft: $($anchor.attr('href')).offset().left
    }, 1000);
    event.preventDefault();
  });
});
    },
    on: function() {
$(function() {
  $('ul.side-nav a').bind('click',function(event){
    var $anchor = $(this);
    /*
    if you want to use one of the easing effects:
    $('html, body').stop().animate({
      scrollLeft: $($anchor.attr('href')).offset().left
    }, 1500,'easeInOutExpo');
     */
    $('html, body').stop().animate({
      scrollLeft: $($anchor.attr('href')).offset().left
    }, 1000);
    event.preventDefault();
  });
});
    },
    off: function() {
    }
  });

  qry2 = Harvey.attach('screen and (max-width:767px)', {
    setup: function() {
$('a[href^="#"]').bind('click.smoothscroll',function (e) {
    e.preventDefault();
    var target = this.hash;
        $target = $(target);
    $('html, body').stop().animate({
        'scrollTop': $target.offset().top
    }, 500, 'swing', function () {
        window.location.hash = target;
    });
});
    },
    on: function() {
$('a[href^="#"]').bind('click.smoothscroll',function (e) {
    e.preventDefault();
    var target = this.hash;
        $target = $(target);
    $('html, body').stop().animate({
        'scrollTop': $target.offset().top
    }, 500, 'swing', function () {
        window.location.hash = target;
    });
});
    },
    off: function() {
    }
  });
}).call(this);
